inherit:
    - ../wandb.yaml
model:
    family: mamba
    n_embd: 512
    n_layer: 8
    n_dims: 1
    interleave: True
training:
    task: high_frequency
    task_kwargs: {}
    data: gaussian
    data_sampler_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 5000
    keep_every_steps: 100000
    train_steps: 100001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
out_dir: ../models/high_frequency
wandb:
    name: "HF_mamba_embd128_layer4_lr1e-4"
