inherit:
    - ../wandb.yaml
model:
    family: mamba
    n_embd: 512
    n_layer: 8
    n_dims: 20
    interleave: True
training:
    task: modulo_classification
    task_kwargs: {}
    data: integer
    data_sampler_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 5000
    keep_every_steps: 100000
    train_steps: 100001
    curriculum:
        dims:
            start: 100  # originally 20
            end: 500  # originally 20
            inc: 50  # originally 1
            interval: 2000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
out_dir: ../models/modulo_classification
wandb:
    name: "MC_mamba_embd512_layer8_lr1e-4"
    # project: cs182_project
    # entity: kkodnad-bair-malik-lab
