inherit:
    - wandb.yaml
model:
    family: gpt2
    n_embd: 128
    n_layer: 2
    n_dims: 20
training:
    task: decision_tree
    task_kwargs: {"depth": 4}
    data: gaussian
    batch_size: 64
    learning_rate: 0.0004
    save_every_steps: 10000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 26
            end: 101
            inc: 5
            interval: 2000
out_dir: ../models/decision_tree
wandb:
    name: "DT_tf_embd128_layer2_lr4e-4"
