inherit:
    - wandb.yaml
model:
    family: gpt2
    n_embd: 512
    n_layer: 8
    n_head: 8
    n_dims: 20
    interleave: True
training:
    task: long_term_dependency
    task_kwargs: {}
    data: gaussian
    data_sampler_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 5000
    keep_every_steps: 100000
    train_steps: 100001
    curriculum:
        dims:
            start: 20
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 64
            end: 64
            inc: 2
            interval: 2000
out_dir: ../models/long_term_dependency
wandb:
    name: "LTD_gpt2_embd512_layer8_lr1e-4"
