inherit:
    - wandb.yaml
model:
    family: gpt2
    n_embd: 128
    n_layer: 2
    n_head: 8
    n_dims: 20
    n_positions: 101
training:
    task: relu_2nn_regression
    task_kwargs: {"hidden_layer_size": 100}
    data: gaussian
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 10000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 26
            end: 101
            inc: 5
            interval: 2000
out_dir: ../models/relu_2nn
wandb:
    name: "2NN_tf_embd128_layer2_lr1e-4"
