inherit:
    - wandb.yaml
model:
    family: gpt2
    n_embd: 512
    n_layer: 8
    n_head: 8
    n_dims: 1
    n_positions: 101
training:
    task: sinusoidal_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 5000
    keep_every_steps: 100000
    train_steps: 100001
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 0
            interval: 2000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
out_dir: ../models/sinusoidal_regression
wandb:
    name: "SR_tf_embd512_layer8_lr1e-4"
