inherit:
    - wandb.yaml
model:
    family: gpt2
    n_embd: 512
    n_layer: 8
    n_head: 8
    n_dims: 10
    n_positions: 101
training:
    task: vector_manipulation
    task_kwargs: {}
    data: uniform
    data_sampler_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 5000
    keep_every_steps: 100000
    train_steps: 100001
    curriculum:
        dims:
            start: 2
            end: 10  
            inc: 2
            interval: 2000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
out_dir: ../models/vector_manipulation
wandb:
    name: "VM_gpt2_embd512_layer8_lr1e-4"
