inherit:
    - ../wandb.yaml
model:
    family: tf-mamba
    n_embd: 128
    n_layer: 4
    n_dims: 20
    interleave: True
    mixed_attn: "standard"  # "standard" or "mambaformer"
    n_positions: 101
training:
    task: linear_regression
    task_kwargs: {}
    data: gaussian
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 10000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
out_dir: ../models/linear_regression
wandb:
    name: "LR_mambaformer_embd128_layer4_lr1e-4"
